
Files already downloaded and verified
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Training:   0% 0/50000 [00:16<?, ?it/s, loss=1.3863]
Traceback (most recent call last):
  File "starter.py", line 24, in <module>
    main(config)
  File "starter.py", line 10, in main
    launcher(config)
  File "/content/drive/MyDrive/Collab_starter/pytorch-gan-collections/launch.py", line 239, in launcher
    train(config)
  File "/content/drive/MyDrive/Collab_starter/pytorch-gan-collections/launch.py", line 214, in train
    }, os.path.join(config.log.logdir + f'/{config.exp.name}', 'model.pt'))
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 379, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 484, in _save
    pickler.dump(obj)
_pickle.PicklingError: Can't pickle <class 'types.Args'>: attribute lookup Args on types failed